[package]
name = "gateway-data-path"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = { version = "1.9.0" }
drain = { version = "0.1", features = ["retain"] }
gateway-messages = { path = "../messages" }
gateway-pubsub-proto = { path = "../pubsub-proto" }
gateway-tables = { path = "../tables" }
h2 = "0.4.7"
thiserror = "2.0.5"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
tokio-util = "0.7.13"
tonic = "0.12"
tracing = "0.1.41"
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }

[dev-dependencies]
gateway-config-grpc = { path = "../config/grpc" }

[build-dependencies]
tonic-build = "0.12"
