[package]
name = "gateway-component"
version = "0.1.0"
publish = false
edition = "2021"
description = """
Base configurable component.
"""

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
thiserror = "2.0.5"
