[package]
name = "gateway-config-grpc"
version = "0.1.0"
publish = false
edition = "2021"
description = """
GRPC configuration utilities.
"""

[dependencies]
duration-str = "0.12.0"
futures = "0.3.31"
gateway-component = { path = "../../component" }
gateway-config-auth = { path = "../auth" }
gateway-config-tls = { path = "../tls" }
http = "1.2.0"
hyper-rustls = { version = "0.27", features = [
    "http2",
    "aws-lc-rs",
], default-features = false }
hyper-util = "0.1.10"
prost = "0.13.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.5"
tokio = "1.42.0"
tonic = { version = "0.12" }
tonic-tls = { version = "0.2.1", default-features = false, features = [
    "rustls",
] }
tower = "0.5.2"
tower-layer = "0.3.3"
tower-service = "0.3.3"
tracing = "0.1.41"

[dev-dependencies]
tracing-test = "0.2.5"

[build-dependencies]
protoc-bin-vendored = "3.1.0"
tonic-build = { version = "0.12.3", features = ["prost"] }
