[package]
name = "agntcy-slim-auth"
version = "0.1.0"
license.workspace = true
edition.workspace = true
description = "Authentication utilities for the Agntcy Slim framework"

[lib]
name = "slim_auth"

[dependencies]
async-trait = { workspace = true }
jsonwebtoken-aws-lc = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
url = { workspace = true }

[dev-dependencies]
base64 = "0.22.1"
openssl = "0.10.73"
wiremock = "0.5"
