[package]
name = "agp-gw-config-tls"
version = "0.1.0"
edition = "2021"
license = { workspace = true }
description = "TLS configuration utilities"

[dependencies]
agp-gw-component = { path = "../../component" }
rustls = "0.23.19"
rustls-native-certs = "0.8.1"
rustls-pki-types = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.5"
tracing = "0.1.41"
