[package]
name = "gateway-config-provider"
version = "0.1.0"
publish = false
edition = "2021"
description = """
TLS configuration utilities.
"""

[dev-dependencies]
tracing = "0.1.41"
tracing-test = "0.2.5"

[dependencies]
serde_yaml = "0.9.34"
thiserror = "2.0.6"
