[package]
name = "agp-gw-config-provider"
version = "0.1.0"
edition = "2021"
license = { workspace = true }
description = "Provider to get configuration from different sources"

[dev-dependencies]
tracing = "0.1.41"
tracing-test = "0.2.5"

[dependencies]
serde_yaml = "0.9.34"
thiserror = "2.0.6"
