# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

tracing:
  log_level: debug
  display_thread_names: true
  display_thread_ids: true
  opentelemetry:
    enabled: true
    service_name: "data-plane-gateway"
    service_version: "v0.1.0"

runtime:
  n_cores: 0
  thread_name: "data-plane-gateway"
  drain_timeout: 10s

services:
  gateway/0:
    server:
      endpoint: "0.0.0.0:46357"
      tls:
        insecure: true

    clients: []
