[package]
name = "gateway-config-auth"
version = "0.1.0"
publish = false
edition = "2021"
description = """
Config for authenticators.
"""

[dependencies]
gateway-tracing = { path = "../../tracing" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.5"
tower-http =  { version = "0.6", features = ["auth"] }

[dev-dependencies]
http = "1.2.0"
tokio = "1.43.0"
tower = "0.5"
tower-reqwest = "0.4.1"
