[package]
name = "agp-gw-config-auth"
version = "0.1.0"
edition = "2021"
license = { workspace = true }
description = "Config for authenticator layers."

[dependencies]
agp-gw-tracing = { path = "../../tracing", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.5"
tower-http =  { version = "0.6", features = ["auth"] }

[dev-dependencies]
http = "1.2.0"
tokio = "1.43.0"
tower = "0.5"
tower-reqwest = "0.4.1"
