[package]
name = "slim-nop-component"
version = "0.1.0"
publish = false
edition = { workspace = true }
license = { workspace = true }

[dependencies]
serde = { workspace = true }
slim-config = { workspace = true }

[dev-dependencies]
serde_yaml = { workspace = true }
