# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "agp.fullname" . }}
  labels:
    {{- include "agp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gw.service.type }}
  ports:
    - port: {{ .Values.gw.service.port }}
      targetPort: messenger
      protocol: TCP
      name: messenger
  selector:
    {{- include "agp.selectorLabels" . | nindent 4 }}
