[package]
name = "gateway-pubsub-proto"
edition = "2021"
publish = false
version = "0.1.0"

[dependencies]
prost = "0.13"
tonic = "0.12.3"

[build-dependencies]
protoc-bin-vendored = "3.1.0"
tonic-build = { version = "0.12.3", features = ["prost"] }
