[package]
name = "agp-pubsub-proto"
edition = "2021"
license = { workspace = true }
version = "0.1.0"

[dependencies]
prost = "0.13"
thiserror = "2.0.5"
tonic = "0.12.3"
tracing = "0.1.41"

[build-dependencies]
protoc-bin-vendored = "3.1.0"
tonic-build = { version = "0.12.3", features = ["prost"] }
