[package]
name = "agp-gw-datapath"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
agp-gw-pubsub-proto = { path = "../pubsub-proto", version = "0.1.0" }
bit-vec = "0.8"
bytes = { version = "1.9.0" }
drain = { version = "0.1", features = ["retain"] }
h2 = "0.4.7"
parking_lot = "0.12"
rand = "0.9.0"
thiserror = "2.0.5"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
tokio-util = "0.7.13"
tonic = "0.12"
tracing = "0.1.41"
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }

[dev-dependencies]
agp-gw-config = { path = "../config" }

[build-dependencies]
tonic-build = "0.12"
