[package]
name = "slim-service"
edition = { workspace = true }
license = { workspace = true }
version = "0.4.2"
description = "Main service and public API to interact with SLIM data plane."

[dependencies]
async-trait = { workspace = true }
drain = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
slim-config = { workspace = true }
slim-controller = { workspace = true }
slim-datapath = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tracing-test = { workspace = true }
