[package]
name = "agp-signal"
edition = "2021"
license = { workspace = true }
version = "0.1.1"
description = "Small library to handle OS signals."

[dependencies]
tokio = { version = "1", features = ["macros", "signal"] }
tracing = "0.1"
