[package]
name = "agp-nop-component"
version = "0.1.0"
publish = false
edition = "2021"
license = { workspace = true }

[dependencies]
agp-config = { path = "../config", version = "0.1.3" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.9.34"
