[package]
name = "agp-nop-component"
version = "0.1.0"
publish = false
edition = { workspace = true }
license = { workspace = true }

[dependencies]
agp-config = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_yaml = { workspace = true }
