[package]
name = "testing"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
publish = false

[[bin]]
name = "workload-gen"
path = "src/bin/workload-gen.rs"

[[bin]]
name = "subscriber"
path = "src/bin/subscriber.rs"

[[bin]]
name = "publisher"
path = "src/bin/publisher.rs"

[dependencies]
agp-config = { workspace = true }
agp-datapath = { workspace = true }
agp-gw = { workspace = true }
agp-service = { workspace = true }
clap = { workspace = true }
indicatif = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
