[package]
name = "testing"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
publish = false

[[bin]]
name = "workload-gen"
path = "src/bin/workload-gen.rs"

[[bin]]
name = "subscriber"
path = "src/bin/subscriber.rs"

[[bin]]
name = "publisher"
path = "src/bin/publisher.rs"

[dependencies]
clap = { workspace = true }
indicatif = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
slim = { workspace = true }
slim-config = { workspace = true }
slim-datapath = { workspace = true }
slim-service = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
