[package]
name = "testing"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "workload-gen"
path = "src/bin/workload-gen.rs"

[[bin]]
name = "subscriber"
path = "src/bin/subscriber.rs"

[[bin]]
name = "publisher"
path = "src/bin/publisher.rs"

[dependencies]
agp-config = { path = "../gateway/config", version = "0.1.6" }
agp-datapath = { path = "../gateway/datapath", version = "0.5.0" }
agp-gw = { path = "../gateway/gateway", version = "0.3.11" }
agp-service = { path = "../gateway/service", version = "0.3.0" }
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17.11"
parking_lot = "0.12"
rand = "0.9.0"
thiserror = "2.0.11"
tokio = "1"
tokio-util = "0.7.13"
tracing = "0.1.41"
