# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

tracing:
  log_level: debug
  display_thread_names: true
  display_thread_ids: true

runtime:
  n_cores: 0
  thread_name: "data-plane-gateway"
  drain_timeout: 10s

services:
  gateway/0:
    pubsub:
      clients:
        - endpoint: "https://localhost:46357"
          tls:
            ca_file: "./config/crypto/server-ca-cert.pem"
          auth:
            basic:
              username: username
              password: ${env:PASSWORD}
