# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---

version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

tasks:
  mcp-proxy:run-mcp-server:
    desc: run mcp server using SSE transport
    cmds:
      - |
        cd examples/mcp-server/
        uv run main.py --port 8000

  mcp-proxy:run-mcp-proxy:
    desc: run mcp proxy
    cmds:
      - cargo run -- --config config/mcp-proxy-config.yaml --svc-name gateway/0 --name org/mcp/proxy --mcp-server http://localhost:8000/sse

  mcp-proxy:run-mcp-client:
    desc: run a simple MCP client that use AGP as transport protocol
    cmds:
      - |
        cd examples/mcp-agp-client
        uv run --reinstall main.py

  mcp-proxy:run-agp:
    desc: run an AGP node
    cmds:
      - |
        cd .. && cargo run --bin gateway -- --config config/base/server-config.yaml
