[package]
name = "agp-gw"
version = "0.3.15"
edition = { workspace = true }
license = { workspace = true }
description = "The main gateway executable."

[[bin]]
name = "gateway"
path = "src/bin/main.rs"

[features]
default = ["multicore"]
multicore = ["tokio/rt-multi-thread", "num_cpus"]

[dependencies]
agp-config = { workspace = true }
agp-service = { workspace = true }
agp-signal = { workspace = true }
agp-tracing = { workspace = true }
clap = { workspace = true }
duration-str = { workspace = true }
lazy_static = { workspace = true }
num_cpus = { version = "1.16.0", optional = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tracing-test = { workspace = true }

[target.x86_64-unknown-linux-gnu.dependencies]
jemallocator = { workspace = true }
