[package]
name = "agp-gw-service"
edition = "2021"
license = { workspace = true }
version = "0.1.0"

[dependencies]
agp-gw-component = { path = "../component", version = "0.1.0" }
agp-gw-config = { path = "../config", version = "0.1.0" }
agp-gw-datapath = { path = "../datapath", version = "0.1.0" }
agp-gw-pubsub-proto = { path = "../pubsub-proto", version = "0.1.0" }
drain = { version = "0.1", features = ["retain"] }
serde = "1.0.217"
thiserror = "2.0.9"
tokio = "1.42.0"
tokio-util = "0.7.13"
tonic = "0.12"
tracing = "0.1.41"

[dev-dependencies]
tracing-test = "0.2.5"
