[package]
name = "agp-service"
edition = "2021"
license = { workspace = true }
version = "0.1.8"
description = "Main service and public API to interact with AGP data plane."

[dependencies]
agp-config = { path = "../config", version = "0.1.5" }
agp-datapath = { path = "../datapath", version = "0.4.0" }
drain = { version = "0.1", features = ["retain"] }
parking_lot = "0.12"
rand = "0.9.0"
serde = "1.0.217"
thiserror = "2.0.9"
tokio = "1.42.0"
tonic = "0.12"
tracing = "0.1.41"

[dev-dependencies]
tracing-test = "0.2.5"
