[package]
name = "gateway-bindings"
edition = "2021"
publish = false
version = "0.1.0"

[lib]
name = "gateway_bindings"
crate-type = ["cdylib", "rlib"]

[dependencies]
gateway-component = { path = "../gateway/component" }
gateway-config-auth = { path = "../gateway/config/auth" }
gateway-config-grpc = { path = "../gateway/config/grpc" }
gateway-config-tls = { path = "../gateway/config/tls" }
gateway-messages = { path = "../gateway/messages" }
gateway-pubsub-proto = { path = "../gateway/pubsub-proto" }
gateway-service = { path = "../gateway/service" }
gateway-tracing = { path = "../gateway/tracing" }
pyo3 = "0.23.3"
pyo3-async-runtimes = { version = "0.23.0", features = ["tokio-runtime"] }
pyo3-stub-gen = "0.7.0"
rand = "0.9.0"
tokio = "1.43.0"
tonic = "0.12"
