[package]
name = "agp-gw-bindings"
edition = "2021"
license = { workspace = true }
publish = false
version = "0.1.0"

[lib]
name = "gateway_bindings"
crate-type = ["cdylib", "rlib"]

[dependencies]
agp-gw-component = { path = "../gateway/component" }
agp-gw-config-auth = { path = "../gateway/config/auth" }
agp-gw-config-grpc = { path = "../gateway/config/grpc" }
agp-gw-config-tls = { path = "../gateway/config/tls" }
agp-gw-messages = { path = "../gateway/messages" }
agp-gw-pubsub-proto = { path = "../gateway/pubsub-proto" }
agp-gw-service = { path = "../gateway/service" }
agp-gw-tracing = { path = "../gateway/tracing" }
pyo3 = "0.23.3"
pyo3-async-runtimes = { version = "0.23.0", features = ["tokio-runtime"] }
pyo3-stub-gen = "0.7.0"
rand = "0.9.0"
tokio = "1.43.0"
tonic = "0.12"
