version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

tasks:
  default:
    cmds:
      - task -l

  run:mcp-server:
    desc: run mcp server
    cmds:
      - |
        cd examples/simple-tool/
        uv run mcp-simple-tool --transport sse --port 8000

  run:mcp-proxy:
    desc: run mcp proxy
    cmds:
      - cargo run -- --config config/mcp-proxy-config.yaml --svc-name gateway/0 --name cisco/mcp/proxy --mcp-server http://localhost:8000/sse

  run:client-example:
    desc: run a simple MCP client that use AGP as transport protocol
    cmds:
      - |
        cd ../agp-mcp/
        uv run tests/agp-client.py

  run:agp:
    desc: run an AGP node
    cmds:
      - |
        cd ../../../data-plane/
        cargo run --bin gateway -- --config config/base/server-config.yaml
