# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---

version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

includes:
  data-plane:
    taskfile: ../../../tasks/rust.yaml
    vars:
      GLOBAL_ARGS: "--workspace"

tasks:
  default:
    cmds:
      - task -l
  mcp-porxy:run-mcp-server:
    desc: run mcp server
    cmds:
      - |
        cd examples/mcp-server/
        uv run main.py --port 8000

  mcp-porxy:run-mcp-server2:
    desc: run mcp server2
    cmds:
      - |
        cd examples/simple-tool/
        uv run mcp-simple-tool --transport sse --port 8000

  mcp-proxy:run-mcp-proxy:
    desc: run mcp proxy
    cmds:
      - cargo run -- --config config/mcp-proxy-config.yaml --svc-name gateway/0 --name cisco/mcp/proxy --mcp-server http://localhost:8000/sse

  mcp-proxy:run-client-example:
    desc: run a simple MCP client that use AGP as transport protocol
    cmds:
      - |
        cd ../agp-mcp/
        uv run tests/agp-client.py

  mcp-proxy:run-agp:
    desc: run an AGP node
    cmds:
      - |
        cd ../../../data-plane/
        cargo run --bin gateway -- --config config/base/server-config.yaml
