# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---

version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

includes:
  mcp-proxy:
    taskfile: ../../../tasks/rust.yaml

vars:
  CARGO_COMPONENTS: "cargo-sort cargo-audit cargo-llvm-cov cargo-machete@0.7.0 cargo-deny@0.17.0 typos-cli"

tasks:
  mcp-proxy:bindings:test:
    desc: "Test the Python bindings"
    cmds:
      - echo "no python bindings exists for mcp-proxy"

  mcp-proxy:lint:
    desc: "Run the linter"
    cmds:
      - task: mcp-proxy:lintall

  mcp-proxy:run-mcp-server:
    desc: run mcp server using SSE transport
    cmds:
      - |
        cd examples/mcp-server/
        uv run main.py --port 8000

  mcp-proxy:run-mcp-proxy:
    desc: run mcp proxy
    cmds:
      - cargo run -- --config config/mcp-proxy-config.yaml --svc-name gateway/0 --name cisco/mcp/proxy --mcp-server http://localhost:8000/sse

  mcp-proxy:run-mcp-client:
    desc: run a simple MCP client that use AGP as transport protocol
    cmds:
      - |
        cd examples/mcp-agp-client
        uv run main.py

  mcp-proxy:run-agp:
    desc: run an AGP node
    cmds:
      - |
        cd ../../../data-plane/
        cargo run --bin gateway -- --config config/base/server-config.yaml
