[workspace]
release_always = true
# do not release packages by default
release = false

[[package]]
name = "agntcy-slim-config"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-datapath"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-nop-component"
publish = false
changelog_update = false

[[package]]
name = "agntcy-slim-service"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-signal"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-tracing"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-bindings"
publish = false
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-controller"
publish = true
release = true
changelog_update = true
