[workspace]
release_always = true
# do not release packages by default
release = false

[[package]]
name = "slim-examples"
publish = false
release = true
changelog_update = true

[[package]]
name = "slim-config"
publish = true
release = true
changelog_update = true

[[package]]
name = "slim-datapath"
publish = true
release = true
changelog_update = true

[[package]]
name = "slim"
publish = true
release = true
changelog_update = true

[[package]]
name = "slim-nop-component"
publish = false
changelog_update = false

[[package]]
name = "slim-service"
publish = true
release = true
changelog_update = true

[[package]]
name = "slim-signal"
publish = true
release = true
changelog_update = true

[[package]]
name = "slim-tracing"
publish = true
release = true
changelog_update = true

[[package]]
name = "slim-bindings"
publish = false
release = true
changelog_update = true

[[package]]
name = "slim-controller"
publish = true
release = true
changelog_update = true
