[workspace]
pr_branch_prefix = "mcp-proxy-"
pr_name = "release {{ package }}-v{{ version }}"
git_tag_name = "{{ package }}-v{{ version }}"

[[package]]
name = "agp-mcp-proxy"
publish = true
release = true
changelog_update = true
