# filepath: /Users/amitami2/personal/AI/IOA/slim/data-plane/examples/src/docker/docker-compose.yml
# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3.8'

services:
  # Slim server
  slim-server:
    build:
      context: ../../../../
      dockerfile: ./data-plane/examples/src/docker/Dockerfile.slim
    ports:
      - "50051:50051"
    networks:
      - slim-network
    volumes:
      - ./config/docker-server-config.yaml:/config/server-config.yaml
    command: ["--config", "/config/server-config.yaml"]

  # Mock agent server
  mock-agent-server:
    build:
      context: ../../../../
      dockerfile: ./data-plane/examples/src/docker/Dockerfile.mock-agent-server
    depends_on:
      - slim-server
    networks:
      - slim-network
    volumes:
      - ./config/docker-client-config.yaml:/config/client-config.yaml
    command: ["--config", "/config/client-config.yaml", "--local-agent", "server", "--remote-agent", "client"]

  # Mock agent client
  mock-agent-client:
    build:
      context: ../../../../
      dockerfile: ./data-plane/examples/src/docker/Dockerfile.mock-agent-client
    depends_on:
      - slim-server
      - mock-agent-server
    networks:
      - slim-network
    volumes:
      - ./config/docker-client-config.yaml:/config/client-config.yaml
    command: ["--config", "/config/client-config.yaml", "--local-agent", "client", "--remote-agent", "server", "--message", "hello from Docker!"]

networks:
  slim-network:
    driver: bridge
