[package]
name = "gateway-tables"
edition = "2021"
publish = false
version = "0.1.0"

[dependencies]
bit-vec = "0.8"
gateway-messages = { path = "../messages" }
parking_lot = "0.12"
rand = "0.9.0"
thiserror = "2.0.5"
tracing = "0.1.41"

[dev-dependencies]
tracing-test = "0.2.5"
