[package]
name = "slim-examples"
version = "0.1.0"
edition = { workspace = true }
publish = false

[[bin]]
name = "sdk-mock"
path = "src/sdk-mock/main.rs"

[dependencies]
slim-config = { workspace = true }
slim-datapath = { workspace = true }
slim = { workspace = true }
slim-service = { workspace = true }
slim-signal = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
