[package]
name = "agp-examples"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "sdk-mock"
path = "src/sdk-mock/main.rs"

[dependencies]
agp-config = { path = "../gateway/config", version = "0.1.5" }
agp-datapath = { path = "../gateway/datapath", version = "0.4.2" }
agp-gw = { path = "../gateway/gateway", version = "0.3.9" }
clap = "4.5"
tokio = "1"
tracing = "0.1.41"
