[package]
name = "gateway-examples"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "sdk-mock"
path = "src/sdk-mock/main.rs"

[dependencies]
clap = "4.5"
gateway = { path = "../gateway/gateway" }
gateway-component = { path = "../gateway/component" }
gateway-messages = { path = "../gateway/messages" }
tokio = "1"
tracing = "0.1.41"
