[package]
name = "agp-examples"
version = "0.1.0"
edition = { workspace = true }
publish = false

[[bin]]
name = "sdk-mock"
path = "src/sdk-mock/main.rs"

[dependencies]
agp-config = { workspace = true }
agp-datapath = { workspace = true }
agp-gw = { workspace = true }
agp-service = { workspace = true }
agp-signal = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true }
tracing = { workspace = true }
