# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

verbose: false

tasks:
  default:
    cmds:
      - task -l

  run:server:
    desc: "Run the server"
    dir: ".."
    cmds:
      - cargo run --bin gateway -- --config ./config/base/server-config.yaml

  run:mock-agent:server:
    desc: "Run the mock agent server"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-agent server --remote-agent client

  run:mock-agent:client:
    desc: "Run the mock agent client"
    dir: src/sdk-mock
    cmds:
      - cargo run -- --config ../../../config/base/client-config.yaml --local-agent client --remote-agent server --message "hey there!"
