[package]
name = "agp-gw-messages"
description = "The main gateway executable"
edition = "2021"
version = "0.1.0"

[dependencies]
agp-gw-pubsub-proto = { path = "../pubsub-proto" }
thiserror = "2.0.5"
tracing = "0.1.41"
