[package]
name = "agp-gw-tracing"
edition = "2021"
version = "0.1.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3.19"

[dev-dependencies]
serde_json = "1.0.137"
