[package]
name = "agp-tracing"
edition = { workspace = true }
license = { workspace = true }
version = "0.2.0"
description = "Observability for AGP data plane: logs, traces and metrics infrastructure."

[dependencies]
agp-config = { path = "../config", version = "0.1.7" }
once_cell = "1.21.0"
opentelemetry = { version = "0.29.0", features = ["trace", "metrics"] }
opentelemetry-otlp = { version = "0.29.0", features = ["metrics", "grpc-tonic"] }
opentelemetry-semantic-conventions = { version = "0.29.0", features = ["semconv_experimental"] }
opentelemetry-stdout = "0.29.0"
opentelemetry_sdk = { version = "0.29.0", default-features = false, features = ["trace", "rt-tokio"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.5"
tracing = "0.1"
tracing-opentelemetry = "0.30.0"
tracing-subscriber = "0.3.19"
uuid = { version = "1.15.1", features = ["v4"] }
