[package]
name = "agp-tracing"
edition = "2021"
license = { workspace = true }
version = "0.1.0"
description = "Observability for AGP data plane: logs, traces and metrics infrastructure."

[dependencies]
opentelemetry = { version = "0.27.0", features = ["trace", "metrics"] }
opentelemetry-otlp = "0.27.0"
opentelemetry-semantic-conventions = "0.27.0"
opentelemetry-stdout = "0.27.0"
opentelemetry_sdk = { version = "0.27.0", default-features = false, features = ["trace", "rt-tokio"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-opentelemetry = "0.28.0"
tracing-subscriber = "0.3.19"

[dev-dependencies]
serde_json = "1.0.137"
