# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

name: ci-test-and-build-control-plane

on:
  push:
    paths:
      - 'control-plane/**'
    branches:
      - main
  pull_request:
    paths:
      - 'control-plane/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}

jobs:
  control-plane-build-and-test:
    name: Control plane - build & test
    uses: ./.github/workflows/reusable-go-build-and-test.yaml

    with:
      go-version: 1.23.6
      working-directory: ./control-plane

    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
