# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
name: ci-test-and-build-data-plane

on:
  push:
    paths:
      - 'data-plane/**'
    branches:
      - main
  pull_request:
    paths:
      - 'data-plane/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  data-plane-build-and-test:
    name: Data plane - build & test
    uses: ./.github/workflows/reusable-rust-build-and-test.yaml
    with:
      working-directory: ./data-plane

  data-plane-build-python-wheels:
    name: Data plane - Python wheels
    uses: ./.github/workflows/reusable-python-build-wheels.yaml

  data-plane-test-release:
    name: Data plane - test release
    runs-on: ubuntu-latest
    needs: [data-plane-build-python-wheels]
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Show files
        run: ls -l dist
