# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-test-and-build-integration-mcp-proxy

on:
  push:
    paths:
      - 'data-plane/integrations/mcp/mcp-proxy/**'
    branches:
      - main
  pull_request:
    paths:
      - 'data-plane/integrations/mcp/mcp-proxy/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  mcp-proxy-build-and-test:
    name: MCP proxy - build & test
    uses: ./.github/workflows/reusable-rust-build-and-test.yaml
    with:
      working-directory: ./data-plane/integrations/mcp/mcp-proxy
      task-prefix: mcp-proxy
