# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  push:
    paths:
      - 'data-plane/**'
    branches:
      - release

jobs:
  # Release unpublished packages.
  # release-plz-release:
  #   name: Release-plz release
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     pull-requests: read
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Rust
  #       uses: ./.github/actions/setup-rust
  #       with:
  #         cache-workspaces: ./data-plane
  #         cache-directories: |
  #           .tools
  #     - name: Run release-plz
  #       uses: release-plz/action@v0.5
  #       with:
  #         command: release
  #         manifest_path: ./data-plane/Cargo.toml
  #         config: ./data-plane/.release-plz.toml
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TEST }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          cache-workspaces: ./data-plane
          cache-directories: |
            .tools
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
          manifest_path: ./data-plane/Cargo.toml
          config: ./data-plane/.release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
