# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-images

on:
  push:
    tags:
      - 'agp-gw-v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  prepare-build:
    name: Prepare Build
    outputs:
      targets: ${{ steps.all-targets.outputs.targets }}
      image-tag: ${{ steps.resolve.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Filter target
        id: resolve
        run: |
          # This assumes tags are in this form
          # agp-<component1>-<component2>-v<version>

          # get version only
          version=${GITHUB_REF_NAME##*-v}

          # set version as output
          echo version=${version} >> ${GITHUB_OUTPUT}

          # Print version
          echo "Version: $version"

      - name: List all targets
        id: all-targets
        uses: docker/bake-action/subaction/list-targets@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67 # v5.5.0

  build-push:
    name: Build docker image - ${{ matrix.target }}
    needs: [prepare-build]
    if: ${{ needs.prepare-build.outputs.targets != '[]' && needs.prepare-build.outputs.targets != '' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare-build.outputs.targets) }}
    uses: ./.github/workflows/reusable-docker-build-push.yaml
    permissions:
      contents: 'read'
      packages: 'write'
      attestations: 'write'
    with:
      bake-target: ${{ matrix.target }}
      image-name: ${{ matrix.target }}
      image-tag: ${{ needs.prepare-build.outputs.image-tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
