# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-rust

on:
  push:
    paths:
      - 'data-plane/**'
    branches:
      - main

jobs:
  # Release unpublished packages.
  release-crates:
    name: Release agp crates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Get components hash
        id: get_hash
        run: |
          COMPONENTS_HASH=$(task data-plane:tools:hash)
          echo "components_hash=$COMPONENTS_HASH" >> $GITHUB_OUTPUT
      - name: Setup Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./data-plane
          cache-directories: |
            .tools
          cache-on-failure: false
          shared-key: ${{runner.os}}-rust-${{hashFiles('**/Cargo.lock')}}-${{ steps.get_hash.outputs.components_hash }}
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
          manifest_path: ./data-plane/Cargo.toml
          config: ./data-plane/.release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-crates-pr:
    name: Release agp crates - PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Get components hash
        id: get_hash
        run: |
          COMPONENTS_HASH=$(task data-plane:tools:hash)
          echo "components_hash=$COMPONENTS_HASH" >> $GITHUB_OUTPUT
      - name: Setup Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./data-plane
          cache-directories: |
            .tools
          cache-on-failure: false
          shared-key: ${{runner.os}}-rust-${{hashFiles('**/Cargo.lock')}}-${{ steps.get_hash.outputs.components_hash }}
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
          manifest_path: ./data-plane/Cargo.toml
          config: ./data-plane/.release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
