# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-python

on:
  push:
    tags:
      - 'agp-bindings-*'
      - 'agp-mcp-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-bindings-wheels:
    name: Data plane - Python wheels
    uses: ./.github/workflows/reusable-python-build-wheels.yaml
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/agp-bindings-')

  build-mcp-wheels:
    name: Data plane - Python wheels
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/agp-mcp-')
    uses: ./.github/workflows/reusable-python-build-and-test.yaml
    with:
      working-directory: ./data-plane/integrations/mcp/agp-mcp
      prefix: integrations

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - build-bindings-wheels
      - build-mcp-wheels
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Show files
        run: ls -l dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
