# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-python

on:
  push:
    branches:
      - main
    paths:
      - 'data-plane/**'
    tags:
      - 'agp-bindings-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-wheels:
    name: Data plane - Python wheels
    uses: ./.github/workflows/reusable-python-build-wheels.yaml
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/agp-bindings-')

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - build-wheels
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/agp-bindings-')
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Show files
        run: ls -l dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
