# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-python

on:
  push:
    tags:
      - 'slim-bindings-v*'
      - 'slim-mcp-v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-bindings-wheels:
    name: Data plane - Python wheels
    uses: ./.github/workflows/reusable-python-build-wheels.yaml
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/slim-bindings-')

  build-mcp-wheels:
    name: Data plane - Python wheels
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/slim-mcp-')
    uses: ./.github/workflows/reusable-python-build-and-test.yaml
    with:
      working-directory: ./data-plane/integrations/mcp/slim-mcp
      prefix: integrations

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - build-bindings-wheels
      - build-mcp-wheels
    if: |
      always() &&
      (needs.build-bindings-wheels.result == 'skipped' || needs.build-bindings-wheels.result == 'success') &&
      (needs.build-mcp-wheels.result == 'skipped' || needs.build-mcp-wheels.result == 'success')
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Show files
        run: ls -l dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
