# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-python

on:
  push:
    branches:
      - main
    paths:
      - 'data-plane/**'
  pull_request:
    paths:
      - 'data-plane/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      released_paths: ${{ steps.release-please.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
          config-file: .github/release-config.json
          manifest-file: .github/release-manifest.json

  build-wheels:
    name: Data plane - Python wheels
    uses: ./.github/workflows/reusable-python-build-wheels.yaml
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/agp-bindings-')

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - build-wheels
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/agp-bindings-')
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Show files
        run: ls -l dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
