# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: python-build-and-test
on:
  workflow_call:

jobs:
  python-bindings-wheels:
    runs-on: ${{ matrix.platform.runner }}
    defaults:
      run:
        shell: bash
        working-directory: ./data-plane/python-bindings
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            os: linux
            target: x86_64
          - runner: ubuntu-22.04-arm
            os: linux
            target: aarch64
          - runner: windows-latest
            os: windows
            target: x64
          - runner: macos-13 # We use macos-13 as it is a x86_64 runner
            os: macos
            target: x86_64
          - runner: macos-15
            os: macos
            target: aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          py-install: false
          poetry-install: false
          uv-install: true
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
      - name: Setup Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./data-plane
          cache-directories: |
            .tools
          cache-on-failure: false
          shared-key: ${{runner.os}}-rust-${{hashFiles('**/Cargo.lock')}}
      - name: Build wheels
        run: |
          task python-bindings:packaging PROFILE=release
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform.os }}-${{ matrix.platform.target }}
          path: ./data-plane/python-bindings/dist
