# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

---
name: go-build-and-test
on:
  workflow_call:

jobs:
  python-bindings-wheels:
    runs-on: ${{ matrix.platform.runner }}
    defaults:
      run:
        shell: bash
        working-directory: ./data-plane
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            os: linux
            target: x86_64
          - runner: ubuntu-24.04-arm
            os: linux
            target: aarch64
          - runner: windows-latest
            os: windows
            target: x64
          - runner: macos-15
            os: macos
            target: x86_64
          - runner: macos-15
            os: macos
            target: aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          py-install: false
          poetry-install: false
          uv-install: true
      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          cache-workspaces: ./data-plane
          cache-directories: |
            .tools
      - name: Set Windows-specific environment variables
        if: matrix.platform.os == 'windows'
        shell: powershell
        run: |
          echo "AWS_LC_SYS_C_STD=-std:c11" >> $env:GITHUB_ENV
      - name: Build wheels
        run: |
          git status
          task data-plane:bindings:python PROFILE=release
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform.os }}-${{ matrix.platform.target }}
          path: ./data-plane/python-bindings/dist

  python-bindings-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
          working-directory: ./data-plane/python-bindings
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: ./data-plane/python-bindings/dist
